export default [
    {
        newsPic: '/img1.jpg',
        newsLink: '#',
        newsCat: 'Finance',
        newsCatLink: '#',
        newsTitle: 'Financial News: A new company is born today at the stock market',
        newsAuthor: 'Christinne Williams',
        newsAuthorLink: '#',
        newsConent: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac leo fermentum, eu cursus nunc maximus. Integer convallis nisi nibh, et ornare neque ullamcorper ac. Nam id congue lectus, a venenatis massa. Maecenas justo libero, vulputate vel nunc id, blandit feugiat sem.',
        newsLikes: '392',
        newsComments: '10',
    },
    {
        newsPic: '/img2.webp',
        newsLink: '#',
        newsCat: 'Finance',
        newsCatLink: '#',
        newsTitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac...',
        newsAuthor: '',
        newsAuthorLink: '',
        newsConent: '',
        newsLikes: '392',
        newsComments: '10',
    },
    {
        newsPic: '/img3.webp',
        newsLink: '#',
        newsCat: 'Finance',
        newsCatLink: '#',
        newsTitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu metus sit amet odio sodales placerat. Sed varius leo ac...',
        newsAuthor: '',
        newsAuthorLink: '',
        newsConent: '',
        newsLikes: '392',
        newsComments: '10',
    },
];